version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: luna
      POSTGRES_USER: luna
      POSTGRES_PASSWORD: luna
    ports:
      - "5432:5432"
  luna:
    build: .
    command: luna init
    depends_on:
      - db
